/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package VISTA;

import CONTROLAR.Metodos;
import MODELO.Movie;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Juan Pablo
 */
public class ModificarPelicula extends javax.swing.JInternalFrame {

    /**
     * Creates new form ModificarPelicula
     */
    public ModificarPelicula() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtablePelicula = new javax.swing.JTable();
        myPanelText = new javax.swing.JPanel();
        btnModificar = new javax.swing.JButton();
        txtTitulo = new javax.swing.JTextField();
        txtDirector = new javax.swing.JTextField();
        txtAnio = new javax.swing.JTextField();
        txtDuracion = new javax.swing.JTextField();
        boxGenero = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        btnTitulo = new javax.swing.JButton();
        btnDirector = new javax.swing.JButton();
        btnAnio = new javax.swing.JButton();
        btnDuracion = new javax.swing.JButton();
        btnGenero = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setTitle("MODIFICAR PELICULA");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jtablePelicula.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtablePelicula);

        btnModificar.setText("MODIFICAR SELECCIÓN");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        boxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GENERO", "ACCION", "ADULTO", "ANIMACION", "AVENTURA", "COMEDIA", "DOCUMENTAL", "DRAMA", "FAMILIAR", "HENTAI ", "INFANTIL", "PARANORMAL", "ROMANCE", "TERROR", " ", " " }));

        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnTitulo.setText("TITULO");
        btnTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTituloActionPerformed(evt);
            }
        });

        btnDirector.setText("DIRECTOR");
        btnDirector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDirectorActionPerformed(evt);
            }
        });

        btnAnio.setText("AÑO");
        btnAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnioActionPerformed(evt);
            }
        });

        btnDuracion.setText("DURACIÓN");
        btnDuracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDuracionActionPerformed(evt);
            }
        });

        btnGenero.setText("GENERO");
        btnGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeneroActionPerformed(evt);
            }
        });

        btnCancelar.setText("CANCELAR ");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout myPanelTextLayout = new javax.swing.GroupLayout(myPanelText);
        myPanelText.setLayout(myPanelTextLayout);
        myPanelTextLayout.setHorizontalGroup(
            myPanelTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myPanelTextLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(myPanelTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(myPanelTextLayout.createSequentialGroup()
                        .addComponent(btnDuracion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(myPanelTextLayout.createSequentialGroup()
                        .addGroup(myPanelTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDirector)
                            .addComponent(btnTitulo)
                            .addComponent(btnAnio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(myPanelTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTitulo)
                            .addGroup(myPanelTextLayout.createSequentialGroup()
                                .addGroup(myPanelTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDirector, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myPanelTextLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(myPanelTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myPanelTextLayout.createSequentialGroup()
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnModificar))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myPanelTextLayout.createSequentialGroup()
                                .addComponent(btnGenero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(boxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myPanelTextLayout.createSequentialGroup()
                        .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(28, 28, 28)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))))
        );
        myPanelTextLayout.setVerticalGroup(
            myPanelTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myPanelTextLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(myPanelTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificar)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(myPanelTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTitulo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(myPanelTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDirector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDirector))
                .addGap(18, 18, 18)
                .addGroup(myPanelTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAnio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(myPanelTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDuracion)
                    .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(myPanelTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGenero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(myPanelTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(myPanelTextLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout myPanel1Layout = new javax.swing.GroupLayout(myPanel1);
        myPanel1.setLayout(myPanel1Layout);
        myPanel1Layout.setHorizontalGroup(
            myPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(myPanelText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        myPanel1Layout.setVerticalGroup(
            myPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(myPanel1Layout.createSequentialGroup()
                .addComponent(myPanelText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(myPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(myPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        m = new Metodos();
        modelo = new DefaultTableModel();
        modelo = m.MostrarTodos();
        jtablePelicula.setModel(modelo);
        txtId.setVisible(false);
        btnTitulo.setVisible(false);
        btnDirector.setVisible(false);
        btnAnio.setVisible(false);
        btnDuracion.setVisible(false);
        btnGenero.setVisible(false);
        btnCancelar.setVisible(false);
        txtTitulo.setVisible(false);
        txtDirector.setVisible(false);
        txtAnio.setVisible(false);
        txtDuracion.setVisible(false);
        boxGenero.setVisible(false);
        btnGuardar.setVisible(false);
        
    }//GEN-LAST:event_formInternalFrameOpened

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        if (jtablePelicula.getSelectedRow()<0) 
        {
            JOptionPane.showMessageDialog(rootPane, "Seleccione un titulo para modificar");
        }else
        {
           
            txtTitulo.setVisible(true);
            txtTitulo.setEditable(false);
            txtDirector.setVisible(true);
            txtDirector.setEditable(false);
            txtAnio.setVisible(true);
            txtAnio.setEditable(false);
            txtDuracion.setVisible(true);
            txtDuracion.setEditable(false);
            //boxGenero.setVisible(true);
            //boxGenero.setEditable(false);
            btnGuardar.setVisible(true);
            btnTitulo.setVisible(true);
            btnDirector.setVisible(true);
            btnAnio.setVisible(true);
            btnDuracion.setVisible(true);
            btnGenero.setVisible(true);
            btnCancelar.setVisible(true);
            modelo = new DefaultTableModel();   
            int pos = jtablePelicula.getSelectedRow();
            modelo = (DefaultTableModel) jtablePelicula.getModel();
            String id = modelo.getValueAt(pos, 0).toString();
            String t = modelo.getValueAt(pos, 1).toString();
            String dd = modelo.getValueAt(pos, 2).toString();
            String g = modelo.getValueAt(pos, 3).toString();
            String a = modelo.getValueAt(pos, 4).toString();
            String du = modelo.getValueAt(pos, 5).toString();
            txtId.setText(id);
            txtTitulo.setText(t);
            txtDirector.setText(dd);
            txtAnio.setText(a);
            txtDuracion.setText(du);
            javax.swing.ComboBoxModel<String> modeloBox = boxGenero.getModel();
            for (int i = 0; i < modeloBox.getSize(); i++) 
            {
                String validar = modeloBox.getElementAt(i).toString();
                if (g.trim().equals(validar)) 
                {
                    boxGenero.setSelectedIndex(i);
                }//FIN VALIDAR EXISTENCIA DEL GENERO
            }// FIN DEL RECORRER EL COMBOBOX GENERO
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
            int id = Integer.parseInt(txtId.getText());
            String titulo = txtTitulo.getText().toUpperCase();
            String director = txtDirector.getText().toUpperCase();
            String anio = txtAnio.getText();
            String duracion = txtDuracion.getText();
            String genero = boxGenero.getSelectedItem().toString();
            Movie mm = new Movie();
            String dura ="";
         
            if (!txtDuracion.isEditable()) 
            {
                for (int i = 0; i < duracion.length(); i++) 
                {
                    try
                    {
                        char r = duracion.charAt(i);
                        int n = Integer.parseInt(String.valueOf(r));
                        dura = dura+n;
                    }catch(Exception e)
                    {
                       //aqui no hara nada, porque no necesito que haga nada 
                    }
                }// fin del for que recorre la variable duracion
                duracion = dura;
            }//fin del if que valida el estado editable del texto de duracion
            
            
            mm = m.validarCampos(titulo, director, anio, duracion, genero);
            if (mm == null) 
            {
                JOptionPane.showMessageDialog(rootPane, "No se pudo actualizar");
            }else
            {
                int actualizar = m.ActualizarPelicula(mm, id);
                if (actualizar>0) 
                {
                    JOptionPane.showMessageDialog(rootPane, "Se actualizo con exito");
                    m = new Metodos();
                    modelo = new DefaultTableModel();
                    modelo = m.MostrarTodos();
                    jtablePelicula.setModel(modelo);
                    txtId.setVisible(false);                  
                    btnTitulo.setVisible(false);
                    btnDirector.setVisible(false);
                    btnAnio.setVisible(false);
                    btnDuracion.setVisible(false);
                    btnGenero.setVisible(false);
                    btnCancelar.setVisible(false);
                    txtTitulo.setVisible(false);
                    txtDirector.setVisible(false);
                    txtAnio.setVisible(false);
                    txtDuracion.setVisible(false);
                    boxGenero.setVisible(false);
                    btnGuardar.setVisible(false);
                    
                }//fin if de validar actualizacion
            }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTituloActionPerformed
        txtTitulo.setEditable(true);
        txtTitulo.setText("");
        txtTitulo.requestFocus();
    }//GEN-LAST:event_btnTituloActionPerformed

    private void btnDirectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDirectorActionPerformed
        txtDirector.setEditable(true);
        txtDirector.setText("");
        txtDirector.requestFocus();
    }//GEN-LAST:event_btnDirectorActionPerformed

    private void btnAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnioActionPerformed
        txtAnio.setEditable(true);
        txtAnio.setText("");
        txtAnio.requestFocus();
    }//GEN-LAST:event_btnAnioActionPerformed

    private void btnDuracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDuracionActionPerformed
        txtDuracion.setEditable(true);
        txtDuracion.setText("");
        txtDuracion.requestFocus();
    }//GEN-LAST:event_btnDuracionActionPerformed

    private void btnGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeneroActionPerformed
        boxGenero.setVisible(true);
    }//GEN-LAST:event_btnGeneroActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        txtTitulo.setText("");
        txtDirector.setText("");
        txtAnio.setText("");
        txtDuracion.setText("");
        boxGenero.setSelectedIndex(0);
        btnTitulo.setVisible(false);
        btnDirector.setVisible(false);
        btnAnio.setVisible(false);
        btnDuracion.setVisible(false);
        btnGenero.setVisible(false);
        btnCancelar.setVisible(false);
        txtTitulo.setVisible(false);
        txtDirector.setVisible(false);
        txtAnio.setVisible(false);
        txtDuracion.setVisible(false);
        boxGenero.setVisible(false);
        btnGuardar.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    //variables
    Metodos m;
    DefaultTableModel modelo;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxGenero;
    private javax.swing.JButton btnAnio;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnDirector;
    private javax.swing.JButton btnDuracion;
    private javax.swing.JButton btnGenero;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtablePelicula;
    private javax.swing.JPanel myPanel1;
    private javax.swing.JPanel myPanelText;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtDirector;
    private javax.swing.JTextField txtDuracion;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
